chore: use changeset

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -335,43 +335,43 @@ jobs:
   #           apk add nodejs npm pnpm
   #           pnpm test
   # test-linux-arm-gnueabihf-binding:
-    name: Test bindings on armv7-unknown-linux-gnueabihf - node@${{ matrix.node }}
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        node:
-          - '14'
-          - '16'
-          - '18'
-    runs-on: ubuntu-latest
-    steps:
-      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
-      - uses: actions/checkout@v3
-      - name: Pnpm Cache
-        uses: ./.github/actions/pnpm-cache
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-armv7-unknown-linux-gnueabihf
-          path: .
-      - name: List packages
-        run: ls -R .
-        shell: bash
-      - name: Install dependencies
-        run: |
-          pnpm config set supportedArchitectures.cpu "arm"
-          pnpm install
-      - name: Setup and run tests
-        uses: addnab/docker-run-action@v3
-        with:
-          image: ghcr.io/napi-rs/napi-rs/nodejs:armhf-${{ matrix.node }}
-          options: '-v ${{ github.workspace }}:/build -w /build'
-          run: |
-            set -e
-            pnpm test
-            ls -la
+  # name: Test bindings on armv7-unknown-linux-gnueabihf - node@${{ matrix.node }}
+  # needs:
+  #   - build
+  # strategy:
+  #   fail-fast: false
+  #   matrix:
+  #     node:
+  #       - '14'
+  #       - '16'
+  #       - '18'
+  # runs-on: ubuntu-latest
+  # steps:
+  #   - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
+  #   - uses: actions/checkout@v3
+  #   - name: Pnpm Cache
+  #     uses: ./.github/actions/pnpm-cache
+  #   - name: Download artifacts
+  #     uses: actions/download-artifact@v3
+  #     with:
+  #       name: bindings-armv7-unknown-linux-gnueabihf
+  #       path: .
+  #   - name: List packages
+  #     run: ls -R .
+  #     shell: bash
+  #   - name: Install dependencies
+  #     run: |
+  #       pnpm config set supportedArchitectures.cpu "arm"
+  #       pnpm install
+  #   - name: Setup and run tests
+  #     uses: addnab/docker-run-action@v3
+  #     with:
+  #       image: ghcr.io/napi-rs/napi-rs/nodejs:armhf-${{ matrix.node }}
+  #       options: '-v ${{ github.workspace }}:/build -w /build'
+  #       run: |
+  #         set -e
+  #         pnpm test
+  #         ls -la
   publish:
     name: Publish
     runs-on: ubuntu-latest
@@ -429,7 +429,7 @@ jobs:
   #         node-version: 16
 
   #     - name: Install Dependencies
-  #       run: 
+  #       run:
 
   #     - name: Create Release Pull Request
   #       uses: changesets/action@v1
